plugins {
	id 'org.springframework.boot'
}

tasks.named('jar') {
	enabled = false
}

dependencies {
	implementation project(':common')

	implementation 'org.springframework.boot:spring-boot-starter-web'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// Swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0'

	// PostgreSQL 드라이버
	runtimeOnly 'org.postgresql:postgresql'
}
